pool:
  name: "Azure Pipelines" 
  vmImage: 'ubuntu-latest'

trigger:
- main

stages:
- stage: buildstage
  displayName: CIpetclinic
  jobs:
  - job: mavenJob
    displayName: maven
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        jdkVersionOption: '1.17'
